# Define common environment variables (explicit configuration required)
x-mongo-variables: &mongo-variables
  MONGODB_USERNAME: ${MONGODB_USERNAME:?MONGODB_USERNAME is required. Please set it in .env file or environment}
  MONGODB_PASSWORD: ${MONGODB_PASSWORD:?MONGODB_PASSWORD is required. Please set it in .env file or environment}
  MONGODB_DATABASE: ${MONGODB_DATABASE:?MONGODB_DATABASE is required. Please set it in .env file or environment}

services:
  mongodb:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
    container_name: notes-mongodb
    environment:
      <<: *mongo-variables
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - notes-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  notes-app:
    build:
      context: .
      dockerfile: notes.Dockerfile
    container_name: notes-app-mongodb
    environment:
      <<: *mongo-variables
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      DB_VENDOR: mongodb
      MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017?authSource=admin
      MONGODB_DB_NAME: ${MONGODB_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - notes-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  notes-network:
    driver: bridge