version: '3.8'

# Define common environment variables (explicit configuration required)
x-couchdb-variables: &couchdb-variables
  COUCHDB_USERNAME: ${COUCHDB_USERNAME:?COUCHDB_USERNAME is required. Please set it in .env file or environment}
  COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:?COUCHDB_PASSWORD is required. Please set it in .env file or environment}
  COUCHDB_DATABASE: ${COUCHDB_DATABASE:?COUCHDB_DATABASE is required. Please set it in .env file or environment}

services:
  couchdb:
    build:
      context: .
      dockerfile: couchdb.Dockerfile
    container_name: notes-couchdb
    environment:
      <<: *couchdb-variables
      COUCHDB_USER: ${COUCHDB_USERNAME}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - notes-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  notes-app:
    build:
      context: .
      dockerfile: notes.Dockerfile
    container_name: notes-app-couchdb
    environment:
      <<: *couchdb-variables
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      DB_VENDOR: couchdb
      COUCHDB_URL: http://${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@couchdb:5984
      COUCHDB_DB_NAME: ${COUCHDB_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - notes-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  couchdb_data:
    driver: local

networks:
  notes-network:
    driver: bridge 